/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RealWorldRouteImport } from './routes/real-world'
import { Route as PrivacyKeysRouteImport } from './routes/privacy-keys'
import { Route as PrecompileMapRouteImport } from './routes/precompile-map'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PoolsRouteImport } from './routes/pools'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as NetworkStatusRouteImport } from './routes/network-status'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EnshrinedAiRouteImport } from './routes/enshrined-ai'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as ChainRouteImport } from './routes/chain'
import { Route as AutonomousAgentsRouteImport } from './routes/autonomous-agents'
import { Route as AuthenticationRouteImport } from './routes/authentication'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentTutorialRouteImport } from './routes/agent-tutorial'
import { Route as AgentSkillsRouteImport } from './routes/agent-skills'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrecompileMapIdRouteImport } from './routes/precompile-map.$id'
import { Route as ApiWalletConfigRouteImport } from './routes/api/wallet-config'
import { Route as AdminVitalsRouteImport } from './routes/admin.vitals'
import { Route as AdminUnlockRouteImport } from './routes/admin.unlock'
import { Route as ApiPublicVitalsRouteImport } from './routes/api/public/vitals'

const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RealWorldRoute = RealWorldRouteImport.update({
  id: '/real-world',
  path: '/real-world',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyKeysRoute = PrivacyKeysRouteImport.update({
  id: '/privacy-keys',
  path: '/privacy-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecompileMapRoute = PrecompileMapRouteImport.update({
  id: '/precompile-map',
  path: '/precompile-map',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsRoute = PoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkStatusRoute = NetworkStatusRouteImport.update({
  id: '/network-status',
  path: '/network-status',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EnshrinedAiRoute = EnshrinedAiRouteImport.update({
  id: '/enshrined-ai',
  path: '/enshrined-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainRoute = ChainRouteImport.update({
  id: '/chain',
  path: '/chain',
  getParentRoute: () => rootRouteImport,
} as any)
const AutonomousAgentsRoute = AutonomousAgentsRouteImport.update({
  id: '/autonomous-agents',
  path: '/autonomous-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationRoute = AuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentTutorialRoute = AgentTutorialRouteImport.update({
  id: '/agent-tutorial',
  path: '/agent-tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/agent-skills',
  path: '/agent-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecompileMapIdRoute = PrecompileMapIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PrecompileMapRoute,
} as any)
const ApiWalletConfigRoute = ApiWalletConfigRouteImport.update({
  id: '/api/wallet-config',
  path: '/api/wallet-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVitalsRoute = AdminVitalsRouteImport.update({
  id: '/admin/vitals',
  path: '/admin/vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnlockRoute = AdminUnlockRouteImport.update({
  id: '/admin/unlock',
  path: '/admin/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVitalsRoute = ApiPublicVitalsRouteImport.update({
  id: '/api/public/vitals',
  path: '/api/public/vitals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent-skills': typeof AgentSkillsRoute
  '/agent-tutorial': typeof AgentTutorialRoute
  '/auth': typeof AuthRoute
  '/authentication': typeof AuthenticationRoute
  '/autonomous-agents': typeof AutonomousAgentsRoute
  '/chain': typeof ChainRoute
  '/deploy': typeof DeployRoute
  '/enshrined-ai': typeof EnshrinedAiRoute
  '/history': typeof HistoryRoute
  '/marketplace': typeof MarketplaceRoute
  '/network-status': typeof NetworkStatusRoute
  '/playground': typeof PlaygroundRoute
  '/pools': typeof PoolsRoute
  '/portfolio': typeof PortfolioRoute
  '/precompile-map': typeof PrecompileMapRouteWithChildren
  '/privacy-keys': typeof PrivacyKeysRoute
  '/real-world': typeof RealWorldRoute
  '/reset-password': typeof ResetPasswordRoute
  '/swap': typeof SwapRoute
  '/admin/unlock': typeof AdminUnlockRoute
  '/admin/vitals': typeof AdminVitalsRoute
  '/api/wallet-config': typeof ApiWalletConfigRoute
  '/precompile-map/$id': typeof PrecompileMapIdRoute
  '/api/public/vitals': typeof ApiPublicVitalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent-skills': typeof AgentSkillsRoute
  '/agent-tutorial': typeof AgentTutorialRoute
  '/auth': typeof AuthRoute
  '/authentication': typeof AuthenticationRoute
  '/autonomous-agents': typeof AutonomousAgentsRoute
  '/chain': typeof ChainRoute
  '/deploy': typeof DeployRoute
  '/enshrined-ai': typeof EnshrinedAiRoute
  '/history': typeof HistoryRoute
  '/marketplace': typeof MarketplaceRoute
  '/network-status': typeof NetworkStatusRoute
  '/playground': typeof PlaygroundRoute
  '/pools': typeof PoolsRoute
  '/portfolio': typeof PortfolioRoute
  '/precompile-map': typeof PrecompileMapRouteWithChildren
  '/privacy-keys': typeof PrivacyKeysRoute
  '/real-world': typeof RealWorldRoute
  '/reset-password': typeof ResetPasswordRoute
  '/swap': typeof SwapRoute
  '/admin/unlock': typeof AdminUnlockRoute
  '/admin/vitals': typeof AdminVitalsRoute
  '/api/wallet-config': typeof ApiWalletConfigRoute
  '/precompile-map/$id': typeof PrecompileMapIdRoute
  '/api/public/vitals': typeof ApiPublicVitalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent-skills': typeof AgentSkillsRoute
  '/agent-tutorial': typeof AgentTutorialRoute
  '/auth': typeof AuthRoute
  '/authentication': typeof AuthenticationRoute
  '/autonomous-agents': typeof AutonomousAgentsRoute
  '/chain': typeof ChainRoute
  '/deploy': typeof DeployRoute
  '/enshrined-ai': typeof EnshrinedAiRoute
  '/history': typeof HistoryRoute
  '/marketplace': typeof MarketplaceRoute
  '/network-status': typeof NetworkStatusRoute
  '/playground': typeof PlaygroundRoute
  '/pools': typeof PoolsRoute
  '/portfolio': typeof PortfolioRoute
  '/precompile-map': typeof PrecompileMapRouteWithChildren
  '/privacy-keys': typeof PrivacyKeysRoute
  '/real-world': typeof RealWorldRoute
  '/reset-password': typeof ResetPasswordRoute
  '/swap': typeof SwapRoute
  '/admin/unlock': typeof AdminUnlockRoute
  '/admin/vitals': typeof AdminVitalsRoute
  '/api/wallet-config': typeof ApiWalletConfigRoute
  '/precompile-map/$id': typeof PrecompileMapIdRoute
  '/api/public/vitals': typeof ApiPublicVitalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agent-skills'
    | '/agent-tutorial'
    | '/auth'
    | '/authentication'
    | '/autonomous-agents'
    | '/chain'
    | '/deploy'
    | '/enshrined-ai'
    | '/history'
    | '/marketplace'
    | '/network-status'
    | '/playground'
    | '/pools'
    | '/portfolio'
    | '/precompile-map'
    | '/privacy-keys'
    | '/real-world'
    | '/reset-password'
    | '/swap'
    | '/admin/unlock'
    | '/admin/vitals'
    | '/api/wallet-config'
    | '/precompile-map/$id'
    | '/api/public/vitals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agent-skills'
    | '/agent-tutorial'
    | '/auth'
    | '/authentication'
    | '/autonomous-agents'
    | '/chain'
    | '/deploy'
    | '/enshrined-ai'
    | '/history'
    | '/marketplace'
    | '/network-status'
    | '/playground'
    | '/pools'
    | '/portfolio'
    | '/precompile-map'
    | '/privacy-keys'
    | '/real-world'
    | '/reset-password'
    | '/swap'
    | '/admin/unlock'
    | '/admin/vitals'
    | '/api/wallet-config'
    | '/precompile-map/$id'
    | '/api/public/vitals'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agent-skills'
    | '/agent-tutorial'
    | '/auth'
    | '/authentication'
    | '/autonomous-agents'
    | '/chain'
    | '/deploy'
    | '/enshrined-ai'
    | '/history'
    | '/marketplace'
    | '/network-status'
    | '/playground'
    | '/pools'
    | '/portfolio'
    | '/precompile-map'
    | '/privacy-keys'
    | '/real-world'
    | '/reset-password'
    | '/swap'
    | '/admin/unlock'
    | '/admin/vitals'
    | '/api/wallet-config'
    | '/precompile-map/$id'
    | '/api/public/vitals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentSkillsRoute: typeof AgentSkillsRoute
  AgentTutorialRoute: typeof AgentTutorialRoute
  AuthRoute: typeof AuthRoute
  AuthenticationRoute: typeof AuthenticationRoute
  AutonomousAgentsRoute: typeof AutonomousAgentsRoute
  ChainRoute: typeof ChainRoute
  DeployRoute: typeof DeployRoute
  EnshrinedAiRoute: typeof EnshrinedAiRoute
  HistoryRoute: typeof HistoryRoute
  MarketplaceRoute: typeof MarketplaceRoute
  NetworkStatusRoute: typeof NetworkStatusRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PoolsRoute: typeof PoolsRoute
  PortfolioRoute: typeof PortfolioRoute
  PrecompileMapRoute: typeof PrecompileMapRouteWithChildren
  PrivacyKeysRoute: typeof PrivacyKeysRoute
  RealWorldRoute: typeof RealWorldRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SwapRoute: typeof SwapRoute
  AdminUnlockRoute: typeof AdminUnlockRoute
  AdminVitalsRoute: typeof AdminVitalsRoute
  ApiWalletConfigRoute: typeof ApiWalletConfigRoute
  ApiPublicVitalsRoute: typeof ApiPublicVitalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-world': {
      id: '/real-world'
      path: '/real-world'
      fullPath: '/real-world'
      preLoaderRoute: typeof RealWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-keys': {
      id: '/privacy-keys'
      path: '/privacy-keys'
      fullPath: '/privacy-keys'
      preLoaderRoute: typeof PrivacyKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precompile-map': {
      id: '/precompile-map'
      path: '/precompile-map'
      fullPath: '/precompile-map'
      preLoaderRoute: typeof PrecompileMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-status': {
      id: '/network-status'
      path: '/network-status'
      fullPath: '/network-status'
      preLoaderRoute: typeof NetworkStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enshrined-ai': {
      id: '/enshrined-ai'
      path: '/enshrined-ai'
      fullPath: '/enshrined-ai'
      preLoaderRoute: typeof EnshrinedAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chain': {
      id: '/chain'
      path: '/chain'
      fullPath: '/chain'
      preLoaderRoute: typeof ChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autonomous-agents': {
      id: '/autonomous-agents'
      path: '/autonomous-agents'
      fullPath: '/autonomous-agents'
      preLoaderRoute: typeof AutonomousAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication': {
      id: '/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-tutorial': {
      id: '/agent-tutorial'
      path: '/agent-tutorial'
      fullPath: '/agent-tutorial'
      preLoaderRoute: typeof AgentTutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-skills': {
      id: '/agent-skills'
      path: '/agent-skills'
      fullPath: '/agent-skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precompile-map/$id': {
      id: '/precompile-map/$id'
      path: '/$id'
      fullPath: '/precompile-map/$id'
      preLoaderRoute: typeof PrecompileMapIdRouteImport
      parentRoute: typeof PrecompileMapRoute
    }
    '/api/wallet-config': {
      id: '/api/wallet-config'
      path: '/api/wallet-config'
      fullPath: '/api/wallet-config'
      preLoaderRoute: typeof ApiWalletConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vitals': {
      id: '/admin/vitals'
      path: '/admin/vitals'
      fullPath: '/admin/vitals'
      preLoaderRoute: typeof AdminVitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/unlock': {
      id: '/admin/unlock'
      path: '/admin/unlock'
      fullPath: '/admin/unlock'
      preLoaderRoute: typeof AdminUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vitals': {
      id: '/api/public/vitals'
      path: '/api/public/vitals'
      fullPath: '/api/public/vitals'
      preLoaderRoute: typeof ApiPublicVitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PrecompileMapRouteChildren {
  PrecompileMapIdRoute: typeof PrecompileMapIdRoute
}

const PrecompileMapRouteChildren: PrecompileMapRouteChildren = {
  PrecompileMapIdRoute: PrecompileMapIdRoute,
}

const PrecompileMapRouteWithChildren = PrecompileMapRoute._addFileChildren(
  PrecompileMapRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentSkillsRoute: AgentSkillsRoute,
  AgentTutorialRoute: AgentTutorialRoute,
  AuthRoute: AuthRoute,
  AuthenticationRoute: AuthenticationRoute,
  AutonomousAgentsRoute: AutonomousAgentsRoute,
  ChainRoute: ChainRoute,
  DeployRoute: DeployRoute,
  EnshrinedAiRoute: EnshrinedAiRoute,
  HistoryRoute: HistoryRoute,
  MarketplaceRoute: MarketplaceRoute,
  NetworkStatusRoute: NetworkStatusRoute,
  PlaygroundRoute: PlaygroundRoute,
  PoolsRoute: PoolsRoute,
  PortfolioRoute: PortfolioRoute,
  PrecompileMapRoute: PrecompileMapRouteWithChildren,
  PrivacyKeysRoute: PrivacyKeysRoute,
  RealWorldRoute: RealWorldRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SwapRoute: SwapRoute,
  AdminUnlockRoute: AdminUnlockRoute,
  AdminVitalsRoute: AdminVitalsRoute,
  ApiWalletConfigRoute: ApiWalletConfigRoute,
  ApiPublicVitalsRoute: ApiPublicVitalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
